# Questions about Rex Kline's book (for Tue., Sept. 10)

## Chapter 1

1. What are the five most widely used model-fitting programs for structural equation modeling (SEM)?

2. Is SEM primarily a confirmatory or primarily an exploratory data analysis technique? Why?

3. What is the difference between "observed" and "latent" variables? Can both types of variables be categorical and continuous in SEM? What is an "indicator"?

4. What is the difference between covariance and correlation? If one changes the unit of measurement (e.g., from meters to centimeters) does this affect the correlation and/or the covariance? What is the relationship between correlation and covariance when both variables have been standardized? 

5. Imagine I want to test a structural equation model with 22 parameters. How many participants do I need to include in my study? 

6. Are multiple regression and SEM fundamentally different data analysis techniques? If yes, what is the fundamental difference? If no, how are the two techniques related to each other?

7. Are the results of SEM analyses generally reported correctly in scientific articles? 

8. Some people call SEM a "disconfirmatory" data analysis technique. Why?

## Chapter 2 (pp. 19-28 only)

9. Which estimation technique is generally used to estimate parameters in multiple regression? Which one is generally used to estimate parameters in SEM? 

10. What is the difference between "standardized" and "unstandardized" estimates in multiple regression analysis? What are beta weights? 

11. Consider "standardized" and "unstandardized" regression coefficients. Which type of coefficients can be directly compared across predictors (same sample)? Which type of coefficients can be directly compared across samples (same predictor)?

12. What is the conceptual meaning of R2? What are two different ways to calculate it, one in the framework of correlation analysis and one in the framework of multiple regression analysis?

13. What is a "specification error"? Under what conditions are specification errors particularly problematic? How can specification errors be avoided? 

14. What is "suppression"?

15. What does Rex Kline think about tools that automatically modify structural models so that they have a better fit? 
