Power Analysis
===============================================================================


```r
# Load my power functions
source("../power.r")
```


## Test of the Close-fit hypothesis


```r
close_fit(df = 5, n = 373)
```

```
## List of 7
##  $ df        : num 5
##  $ n         : num 373
##  $ rmsea0    : num 0.05
##  $ rmseaa    : num 0.08
##  $ alpha     : num 0.05
##  $ hypothesis: chr "Close-fit hypothesis"
##  $ power     : num 0.317
##  - attr(*, "class")= chr "PowerSummary"
```


Interpretation: if this model actually does not have close fit in the population, then the estimated probability that we can reject this incorrect model is 31.7%.

## Test of the Not-close-fit hypothesis


```r
not_close_fit(df = 5, n = 373)
```

```
## List of 7
##  $ df        : num 5
##  $ n         : num 373
##  $ rmsea0    : num 0.05
##  $ rmseaa    : num 0.01
##  $ alpha     : num 0.05
##  $ hypothesis: chr "Not-close-fit hypothesis"
##  $ power     : num 0.229
##  - attr(*, "class")= chr "PowerSummary"
```


Interpretation: if this model actually has close fit in the population, then the estimated probability that we can detect this correct model is 22.9%.

***


```r
sessionInfo()
```

```
## R version 3.0.2 (2013-09-25)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] knitr_1.5
## 
## loaded via a namespace (and not attached):
## [1] evaluate_0.5.1 formatR_0.10   stringr_0.6.2  tools_3.0.2
```

